services:
    postgres:
        image: 'postgres:latest'
        environment:
            - 'POSTGRES_DB=certdb'
            - 'POSTGRES_PASSWORD=123'
            - 'POSTGRES_USER=admin'
        ports:
            - '5431:5432'
